package com.AK.Jpeproject.SpringData_JPA_OnlineGroceryStore.Controller;

import com.AK.Jpeproject.SpringData_JPA_OnlineGroceryStore.Oracle1.Entity.OnlineGroceryStore;
import com.AK.Jpeproject.SpringData_JPA_OnlineGroceryStore.Service.OnlineGroceryStoreService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.repository.query.Param;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.util.List;

@RestController
public class OnlineGroceryStoreController {

    @Autowired
    private OnlineGroceryStoreService onlineGroceryStoreService;


    //pass an inputs in JSON format under body in Postman and store/add in Table/Pojo of OnlineGroceryStore

    /**
     * This is the sample JSON , similar would be passed in postman.serialNumber is autogenerated so no need to pass
     * {
     * "empCity" : "Panipat",
     * "empDept" : "IT",
     * "empName" : "Anil",
     * "empState" : "Haryana"
     * }
     * @param onlineGroceryStore
     * @return
     */

    /**
     * Insert a record in Grocery Store.
     *
     * @param onlineGroceryStore
     * @return
     */
    @PostMapping("/insertAnItem")
    public ResponseEntity<Void> insertAnItem(@RequestBody OnlineGroceryStore onlineGroceryStore) {
        System.out.println("Attempting to insert a record in GroceryStoreTable: " + onlineGroceryStore);
        return onlineGroceryStoreService.insertAnItemInGroceryStore(onlineGroceryStore);    //  return new ResponseEntity<>(onlineGroceryStore, HttpStatus.CREATED);
    }

    /**
     * Get a record using a serial Number from Grocery Store
     *
     * @param serialNumber
     * @return
     */
    @GetMapping("getRecordFromGroceryStore/{serialNumber}")
    public ResponseEntity<OnlineGroceryStore> getRecordFromGroceryStore(@PathVariable("serialNumber") Long serialNumber) {
        return onlineGroceryStoreService.getRecordFromGroceryStore(serialNumber);
    }

    /**
     * getAllRecords from Grocery Store
     *
     * @return
     */
    @GetMapping("/getAllRecordsFromGroceryStore")
    public ResponseEntity<List<OnlineGroceryStore>> getAlleRecordsFromGroceryStore() {
        return onlineGroceryStoreService.getAllTheRecordsFromGroceryStore();
    }

    /**
     * Delete a record from grocery_Store table using serial number
     *
     * @param serialNumber
     * @return
     */
    @DeleteMapping("/deleteRecordFromGroceryStore/{serialNumber}")
    public ResponseEntity<Void> deleteTheRecordFromGroceryStore(@PathVariable("serialNumber") Long serialNumber) {
        return onlineGroceryStoreService.deleteTheRecordFromGroceryStoreTable(serialNumber);
    }

    /**
     * Update an existing Record in Grocery Store table
     *
     * @param serialNumber
     * @param onlineGroceryStore
     * @return
     */
    @PutMapping("/updateRecordInGroceryStore/{serialNumber}")
    public ResponseEntity<Void> updateRecord(@PathVariable Long serialNumber, @RequestBody OnlineGroceryStore onlineGroceryStore) {
        System.out.println("entering");
        return onlineGroceryStoreService.insertUpdateRecordInGroceryStore(serialNumber, onlineGroceryStore);
    }

    @GetMapping("/getCountOfRecordsInGroceryStore")
    public ResponseEntity<Long> getCountOfRecordsInGroceryStore() {
        return onlineGroceryStoreService.getCountOfRecordsInGSTable();
    }

    @GetMapping("/getTotalBillAmountInGroceryStore")
    public ResponseEntity<Double> getTotalBillAmtInGroceryStore() {
        return onlineGroceryStoreService.getTotalBillAmtInGSTable();
    }

    //not working
    @GetMapping("/getRecordsWithinDateRange")
    public ResponseEntity<?> getRecordsWithinDateRange() {
        return onlineGroceryStoreService.getRecordsWithinADateRange();
    }

    //Not implemented
//    @GetMapping("/getTotalAmtOfSaleOnDailybasis")
//    public ResponseEntity<?> getTotalAmtOfSaleOnDailybasis() {
//        return onlineGroceryStoreService.getTotalAmtOfSaleOnDailybasis();
//    }
//max of quantity
    @GetMapping("/getMaxQuantityInGroceryStore")   //Highest sold item
    public ResponseEntity<?> getMaxQuantityInGroceryStore() {
        return onlineGroceryStoreService.getMaxQuantityInGroceryStore();

    }

    @GetMapping("/getTotalAmtOfSaleByDates")
    public ResponseEntity<?> getTotalAmtOfSaleByDates() {
        return onlineGroceryStoreService.getTotalAmtOfSaleByDates();

    }

    @GetMapping("/getItemNameByPhoneDate/{phoneNumber}/{itemInsertDate}")
    public ResponseEntity<?> getItemNameByPhoneDate(@PathVariable("phoneNumber") String phoneNumber, @PathVariable("itemInsertDate") @DateTimeFormat LocalDate itemInsertDate) {
        System.out.println("inputs: "+phoneNumber+", "+itemInsertDate);
        return onlineGroceryStoreService.getItemNameByPhoneDate(phoneNumber,itemInsertDate);
    }
}